alter table ora_advisors add column if not exists trusted boolean not null default false;
alter table ora_advisors add column if not exists is_new boolean not null default false;
alter table ora_advisors add column if not exists rating numeric(2,1) not null default 4.8;
alter table ora_advisors add column if not exists reviews integer not null default 120;

update ora_advisors set trusted = true, rating = 4.9, reviews = 2140 where id = 'adv_mira';
update ora_advisors set trusted = true, rating = 4.9, reviews = 1864 where id = 'adv_rowan';
update ora_advisors set trusted = true, rating = 4.8, reviews = 1512 where id = 'adv_imani';
update ora_advisors set trusted = true, rating = 4.8, reviews = 980 where id = 'adv_soren';

insert into ora_advisors (id, user_id, name, slug, bio, experience, specialties, rate_coins, photo_url, video_url, status, trusted, is_new, rating, reviews)
values
  ('adv_lila', 'seed:lila', 'Lila Chen', 'lila',
   'Love readings that stay honest. Lila names the pattern, then the next move.',
   '8 years of tarot and relationship sittings, in person and online.',
   'Love, Tarot, Twin flame',
   21, '/images/lila.jpg', '', 'live', false, true, 4.8, 86),
  ('adv_mateo', 'seed:mateo', 'Mateo Cruz', 'mateo',
   'Work, money, and the conversation you keep postponing. Mateo is practical.',
   '11 years of career and business readings for people changing jobs.',
   'Career, Money, Clarity',
   19, '/images/mateo.jpg', '', 'live', false, true, 4.7, 64),
  ('adv_nadia', 'seed:nadia', 'Nadia El-Amin', 'nadia',
   'Birth charts and the month ahead. Nadia keeps astrology in the room, not the sky.',
   '14 years as a consulting astrologer. Hellenistic technique, modern language.',
   'Astrology, Birth chart, Transits',
   23, '/images/nadia.jpg', '', 'live', false, true, 4.9, 112),
  ('adv_theo', 'seed:theo', 'Theo Park', 'theo',
   'Mediumship for family and the animals people still talk to. Quiet, no theatre.',
   '20 years of private sittings. Former chaplain.',
   'Medium, Family, Pets',
   26, '/images/theo.jpg', '', 'live', false, true, 4.8, 73),
  ('adv_freya', 'seed:freya', 'Freya Nilsen', 'freya',
   'Runes, protection, and the thing circling the house. Freya is spare with words.',
   '16 years of rune work and private protection sittings.',
   'Runes, Protection, Guidance',
   24, '/images/freya.jpg', '', 'live', true, true, 4.9, 408),
  ('adv_amara', 'seed:amara', 'Amara Okonkwo', 'amara',
   'Ancestral work and the life path that keeps repeating. Amara sits you down.',
   '22 years of ancestral and healing readings across two continents.',
   'Ancestral, Healing, Life path',
   27, '/images/amara.jpg', '', 'live', true, true, 5.0, 692),
  ('adv_jules', 'seed:jules', 'Jules Marlowe', 'jules',
   'Breakups, almosts, and whether to text. Jules is fast and kind.',
   '6 years of love and timing readings. New to the floor this month.',
   'Love, Breakups, Timing',
   16, '/images/jules.jpg', '', 'live', false, true, 4.7, 41),
  ('adv_priya', 'seed:priya', 'Priya Raman', 'priya',
   'Vedic charts for marriage and work. Priya is precise; she will say wait.',
   '15 years of Vedic consulting for families and professionals.',
   'Vedic, Marriage, Career',
   25, '/images/priya.jpg', '', 'live', true, true, 4.9, 540),
  ('adv_cass', 'seed:cass', 'Cass Whitaker', 'cass',
   'Dreams, symbols, and the night work you cannot shake. Cass listens first.',
   '9 years of dreamwork and symbol readings.',
   'Dreams, Symbols, Night work',
   18, '/images/cass.jpg', '', 'live', false, true, 4.6, 38),
  ('adv_elena', 'seed:elena', 'Elena Varga', 'elena',
   'Palm, first impressions, and the decision already in your hand.',
   '30 years of palmistry in cafés and private rooms.',
   'Palm, Decisions, First impressions',
   20, '/images/elena.jpg', '', 'live', false, true, 4.8, 97),
  ('adv_kai', 'seed:kai', 'Kai Nakamura', 'kai',
   'Energy, blocks, and why the same week keeps returning. Kai is exact.',
   '10 years of energy and aura sittings. Trained in Tokyo and Lisbon.',
   'Energy, Aura, Blockages',
   22, '/images/kai.jpg', '', 'live', false, true, 4.7, 55),
  ('adv_wren', 'seed:wren', 'Wren Solis', 'wren',
   'New moons, rituals, and the wish you keep rewriting. Wren is new and busy.',
   '4 years of moon work and manifestation sittings.',
   'New moon, Manifest, Ritual',
   15, '/images/wren.jpg', '', 'live', false, true, 4.6, 29),
  ('adv_dominic', 'seed:dominic', 'Dominic Hart', 'dominic',
   'Yes, no, and the next honest step. Dominic does not pad the answer.',
   '12 years of decision readings for founders and people leaving.',
   'Decisions, Clarity, Yes or no',
   19, '/images/dominic.jpg', '', 'live', false, true, 4.8, 77),
  ('adv_yasmin', 'seed:yasmin', 'Yasmin Darwish', 'yasmin',
   'Family, culture, and the future you are building around other people.',
   '13 years of family and future sittings. Bilingual rooms.',
   'Family, Future, Love',
   21, '/images/yasmin.jpg', '', 'live', false, true, 4.8, 61)
on conflict (id) do nothing;
