/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdvisorRouteRouteImport } from './routes/advisor/route'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdvisorsRouteImport } from './routes/admin/advisors'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminPromosRouteImport } from './routes/admin/promos'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTrustedRouteImport } from './routes/admin/trusted'
import { Route as AdvisorIndexRouteImport } from './routes/advisor/index'
import { Route as AdvisorActivityRouteImport } from './routes/advisor/activity'
import { Route as AdvisorAppliedRouteImport } from './routes/advisor/applied'
import { Route as AdvisorCustomersRouteImport } from './routes/advisor/customers'
import { Route as AdvisorEarningsRouteImport } from './routes/advisor/earnings'
import { Route as AdvisorInboxRouteImport } from './routes/advisor/inbox'
import { Route as AdvisorLoginRouteImport } from './routes/advisor/login'
import { Route as AdvisorNotesRouteImport } from './routes/advisor/notes'
import { Route as AdvisorProfileRouteImport } from './routes/advisor/profile'
import { Route as AdvisorReadingsRouteImport } from './routes/advisor/readings'
import { Route as AdvisorSettingsRouteImport } from './routes/advisor/settings'
import { Route as AdvisorSignupRouteImport } from './routes/advisor/signup'
import { Route as AdvisorTodoRouteImport } from './routes/advisor/todo'
import { Route as AdvisorsIndexRouteImport } from './routes/advisors/index'
import { Route as AdvisorsIdRouteImport } from './routes/advisors/$id'
import { Route as ApiPayRouteImport } from './routes/api/pay'
import { Route as ApiQaStateRouteImport } from './routes/api/qa-state'
import { Route as ReadingIdRouteImport } from './routes/reading/$id'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as SupportIdRouteImport } from './routes/support/$id'
import { Route as WaitIdRouteImport } from './routes/wait/$id'
import { Route as AdminSupportIndexRouteImport } from './routes/admin/support/index'
import { Route as AdminSupportIdRouteImport } from './routes/admin/support/$id'
import { Route as AdvisorCustomersIdRouteImport } from './routes/advisor/customers.$id'
import { Route as AdvisorProfileEditRouteImport } from './routes/advisor/profile.edit'
import { Route as AdvisorSessionIdRouteImport } from './routes/advisor/session/$id'
import { Route as AdvisorSettingsBlockedRouteImport } from './routes/advisor/settings.blocked'
import { Route as AdvisorSettingsFaqRouteImport } from './routes/advisor/settings.faq'
import { Route as AdvisorSettingsRepliesRouteImport } from './routes/advisor/settings.replies'
import { Route as AdvisorSettingsReviewsRouteImport } from './routes/advisor/settings.reviews'
import { Route as AdvisorSettingsSecurityRouteImport } from './routes/advisor/settings.security'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRouteRoute = AdvisorRouteRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdvisorsRoute = AdminAdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTrustedRoute = AdminTrustedRouteImport.update({
  id: '/trusted',
  path: '/trusted',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorActivityRoute = AdvisorActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorAppliedRoute = AdvisorAppliedRouteImport.update({
  id: '/applied',
  path: '/applied',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorCustomersRoute = AdvisorCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorEarningsRoute = AdvisorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorInboxRoute = AdvisorInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorLoginRoute = AdvisorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorNotesRoute = AdvisorNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorProfileRoute = AdvisorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorReadingsRoute = AdvisorReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorSettingsRoute = AdvisorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorSignupRoute = AdvisorSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorTodoRoute = AdvisorTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorsIndexRoute = AdvisorsIndexRouteImport.update({
  id: '/advisors/',
  path: '/advisors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsIdRoute = AdvisorsIdRouteImport.update({
  id: '/advisors/$id',
  path: '/advisors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayRoute = ApiPayRouteImport.update({
  id: '/api/pay',
  path: '/api/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQaStateRoute = ApiQaStateRouteImport.update({
  id: '/api/qa-state',
  path: '/api/qa-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingIdRoute = ReadingIdRouteImport.update({
  id: '/reading/$id',
  path: '/reading/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitIdRoute = WaitIdRouteImport.update({
  id: '/wait/$id',
  path: '/wait/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportIndexRoute = AdminSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSupportIdRoute = AdminSupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdvisorCustomersIdRoute = AdvisorCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdvisorCustomersRoute,
} as any)
const AdvisorProfileEditRoute = AdvisorProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdvisorProfileRoute,
} as any)
const AdvisorSessionIdRoute = AdvisorSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AdvisorRouteRoute,
} as any)
const AdvisorSettingsBlockedRoute = AdvisorSettingsBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AdvisorSettingsRoute,
} as any)
const AdvisorSettingsFaqRoute = AdvisorSettingsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdvisorSettingsRoute,
} as any)
const AdvisorSettingsRepliesRoute = AdvisorSettingsRepliesRouteImport.update({
  id: '/replies',
  path: '/replies',
  getParentRoute: () => AdvisorSettingsRoute,
} as any)
const AdvisorSettingsReviewsRoute = AdvisorSettingsReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdvisorSettingsRoute,
} as any)
const AdvisorSettingsSecurityRoute = AdvisorSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdvisorSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/advisor': typeof AdvisorRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/apply': typeof ApplyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/admin/advisors': typeof AdminAdvisorsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trusted': typeof AdminTrustedRoute
  '/advisor/activity': typeof AdvisorActivityRoute
  '/advisor/applied': typeof AdvisorAppliedRoute
  '/advisor/customers': typeof AdvisorCustomersRouteWithChildren
  '/advisor/earnings': typeof AdvisorEarningsRoute
  '/advisor/inbox': typeof AdvisorInboxRoute
  '/advisor/login': typeof AdvisorLoginRoute
  '/advisor/notes': typeof AdvisorNotesRoute
  '/advisor/profile': typeof AdvisorProfileRouteWithChildren
  '/advisor/readings': typeof AdvisorReadingsRoute
  '/advisor/settings': typeof AdvisorSettingsRouteWithChildren
  '/advisor/signup': typeof AdvisorSignupRoute
  '/advisor/todo': typeof AdvisorTodoRoute
  '/advisors/$id': typeof AdvisorsIdRoute
  '/api/pay': typeof ApiPayRoute
  '/api/qa-state': typeof ApiQaStateRoute
  '/reading/$id': typeof ReadingIdRoute
  '/support/$id': typeof SupportIdRoute
  '/wait/$id': typeof WaitIdRoute
  '/admin/': typeof AdminIndexRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/advisors/': typeof AdvisorsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/advisor/customers/$id': typeof AdvisorCustomersIdRoute
  '/advisor/profile/edit': typeof AdvisorProfileEditRoute
  '/advisor/session/$id': typeof AdvisorSessionIdRoute
  '/advisor/settings/blocked': typeof AdvisorSettingsBlockedRoute
  '/advisor/settings/faq': typeof AdvisorSettingsFaqRoute
  '/advisor/settings/replies': typeof AdvisorSettingsRepliesRoute
  '/advisor/settings/reviews': typeof AdvisorSettingsReviewsRoute
  '/advisor/settings/security': typeof AdvisorSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/support/': typeof AdminSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/apply': typeof ApplyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/admin/advisors': typeof AdminAdvisorsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trusted': typeof AdminTrustedRoute
  '/advisor/activity': typeof AdvisorActivityRoute
  '/advisor/applied': typeof AdvisorAppliedRoute
  '/advisor/customers': typeof AdvisorCustomersRouteWithChildren
  '/advisor/earnings': typeof AdvisorEarningsRoute
  '/advisor/inbox': typeof AdvisorInboxRoute
  '/advisor/login': typeof AdvisorLoginRoute
  '/advisor/notes': typeof AdvisorNotesRoute
  '/advisor/profile': typeof AdvisorProfileRouteWithChildren
  '/advisor/readings': typeof AdvisorReadingsRoute
  '/advisor/settings': typeof AdvisorSettingsRouteWithChildren
  '/advisor/signup': typeof AdvisorSignupRoute
  '/advisor/todo': typeof AdvisorTodoRoute
  '/advisors/$id': typeof AdvisorsIdRoute
  '/api/pay': typeof ApiPayRoute
  '/api/qa-state': typeof ApiQaStateRoute
  '/reading/$id': typeof ReadingIdRoute
  '/support/$id': typeof SupportIdRoute
  '/wait/$id': typeof WaitIdRoute
  '/admin': typeof AdminIndexRoute
  '/advisor': typeof AdvisorIndexRoute
  '/advisors': typeof AdvisorsIndexRoute
  '/support': typeof SupportIndexRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/advisor/customers/$id': typeof AdvisorCustomersIdRoute
  '/advisor/profile/edit': typeof AdvisorProfileEditRoute
  '/advisor/session/$id': typeof AdvisorSessionIdRoute
  '/advisor/settings/blocked': typeof AdvisorSettingsBlockedRoute
  '/advisor/settings/faq': typeof AdvisorSettingsFaqRoute
  '/advisor/settings/replies': typeof AdvisorSettingsRepliesRoute
  '/advisor/settings/reviews': typeof AdvisorSettingsReviewsRoute
  '/advisor/settings/security': typeof AdvisorSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/support': typeof AdminSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/advisor': typeof AdvisorRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/apply': typeof ApplyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/admin/advisors': typeof AdminAdvisorsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trusted': typeof AdminTrustedRoute
  '/advisor/activity': typeof AdvisorActivityRoute
  '/advisor/applied': typeof AdvisorAppliedRoute
  '/advisor/customers': typeof AdvisorCustomersRouteWithChildren
  '/advisor/earnings': typeof AdvisorEarningsRoute
  '/advisor/inbox': typeof AdvisorInboxRoute
  '/advisor/login': typeof AdvisorLoginRoute
  '/advisor/notes': typeof AdvisorNotesRoute
  '/advisor/profile': typeof AdvisorProfileRouteWithChildren
  '/advisor/readings': typeof AdvisorReadingsRoute
  '/advisor/settings': typeof AdvisorSettingsRouteWithChildren
  '/advisor/signup': typeof AdvisorSignupRoute
  '/advisor/todo': typeof AdvisorTodoRoute
  '/advisors/$id': typeof AdvisorsIdRoute
  '/api/pay': typeof ApiPayRoute
  '/api/qa-state': typeof ApiQaStateRoute
  '/reading/$id': typeof ReadingIdRoute
  '/support/$id': typeof SupportIdRoute
  '/wait/$id': typeof WaitIdRoute
  '/admin/': typeof AdminIndexRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/advisors/': typeof AdvisorsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/advisor/customers/$id': typeof AdvisorCustomersIdRoute
  '/advisor/profile/edit': typeof AdvisorProfileEditRoute
  '/advisor/session/$id': typeof AdvisorSessionIdRoute
  '/advisor/settings/blocked': typeof AdvisorSettingsBlockedRoute
  '/advisor/settings/faq': typeof AdvisorSettingsFaqRoute
  '/advisor/settings/replies': typeof AdvisorSettingsRepliesRoute
  '/advisor/settings/reviews': typeof AdvisorSettingsReviewsRoute
  '/advisor/settings/security': typeof AdvisorSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/support/': typeof AdminSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisor'
    | '/account'
    | '/apply'
    | '/forgot-password'
    | '/leads'
    | '/login'
    | '/me'
    | '/membership'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/terms'
    | '/work'
    | '/admin/advisors'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/payouts'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/trusted'
    | '/advisor/activity'
    | '/advisor/applied'
    | '/advisor/customers'
    | '/advisor/earnings'
    | '/advisor/inbox'
    | '/advisor/login'
    | '/advisor/notes'
    | '/advisor/profile'
    | '/advisor/readings'
    | '/advisor/settings'
    | '/advisor/signup'
    | '/advisor/todo'
    | '/advisors/$id'
    | '/api/pay'
    | '/api/qa-state'
    | '/reading/$id'
    | '/support/$id'
    | '/wait/$id'
    | '/admin/'
    | '/advisor/'
    | '/advisors/'
    | '/support/'
    | '/admin/support/$id'
    | '/advisor/customers/$id'
    | '/advisor/profile/edit'
    | '/advisor/session/$id'
    | '/advisor/settings/blocked'
    | '/advisor/settings/faq'
    | '/advisor/settings/replies'
    | '/advisor/settings/reviews'
    | '/advisor/settings/security'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/admin/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/apply'
    | '/forgot-password'
    | '/leads'
    | '/login'
    | '/me'
    | '/membership'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/terms'
    | '/work'
    | '/admin/advisors'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/payouts'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/trusted'
    | '/advisor/activity'
    | '/advisor/applied'
    | '/advisor/customers'
    | '/advisor/earnings'
    | '/advisor/inbox'
    | '/advisor/login'
    | '/advisor/notes'
    | '/advisor/profile'
    | '/advisor/readings'
    | '/advisor/settings'
    | '/advisor/signup'
    | '/advisor/todo'
    | '/advisors/$id'
    | '/api/pay'
    | '/api/qa-state'
    | '/reading/$id'
    | '/support/$id'
    | '/wait/$id'
    | '/admin'
    | '/advisor'
    | '/advisors'
    | '/support'
    | '/admin/support/$id'
    | '/advisor/customers/$id'
    | '/advisor/profile/edit'
    | '/advisor/session/$id'
    | '/advisor/settings/blocked'
    | '/advisor/settings/faq'
    | '/advisor/settings/replies'
    | '/advisor/settings/reviews'
    | '/advisor/settings/security'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/admin/support'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisor'
    | '/account'
    | '/apply'
    | '/forgot-password'
    | '/leads'
    | '/login'
    | '/me'
    | '/membership'
    | '/reset-password'
    | '/signup'
    | '/studio'
    | '/terms'
    | '/work'
    | '/admin/advisors'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/payouts'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/trusted'
    | '/advisor/activity'
    | '/advisor/applied'
    | '/advisor/customers'
    | '/advisor/earnings'
    | '/advisor/inbox'
    | '/advisor/login'
    | '/advisor/notes'
    | '/advisor/profile'
    | '/advisor/readings'
    | '/advisor/settings'
    | '/advisor/signup'
    | '/advisor/todo'
    | '/advisors/$id'
    | '/api/pay'
    | '/api/qa-state'
    | '/reading/$id'
    | '/support/$id'
    | '/wait/$id'
    | '/admin/'
    | '/advisor/'
    | '/advisors/'
    | '/support/'
    | '/admin/support/$id'
    | '/advisor/customers/$id'
    | '/advisor/profile/edit'
    | '/advisor/session/$id'
    | '/advisor/settings/blocked'
    | '/advisor/settings/faq'
    | '/advisor/settings/replies'
    | '/advisor/settings/reviews'
    | '/advisor/settings/security'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/admin/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AdvisorRouteRoute: typeof AdvisorRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  ApplyRoute: typeof ApplyRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  MembershipRoute: typeof MembershipRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  WorkRoute: typeof WorkRoute
  AdvisorsIdRoute: typeof AdvisorsIdRoute
  ApiPayRoute: typeof ApiPayRoute
  ApiQaStateRoute: typeof ApiQaStateRoute
  ReadingIdRoute: typeof ReadingIdRoute
  SupportIdRoute: typeof SupportIdRoute
  WaitIdRoute: typeof WaitIdRoute
  AdvisorsIndexRoute: typeof AdvisorsIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/advisors': {
      id: '/admin/advisors'
      path: '/advisors'
      fullPath: '/admin/advisors'
      preLoaderRoute: typeof AdminAdvisorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/trusted': {
      id: '/admin/trusted'
      path: '/trusted'
      fullPath: '/admin/trusted'
      preLoaderRoute: typeof AdminTrustedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/activity': {
      id: '/advisor/activity'
      path: '/activity'
      fullPath: '/advisor/activity'
      preLoaderRoute: typeof AdvisorActivityRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/applied': {
      id: '/advisor/applied'
      path: '/applied'
      fullPath: '/advisor/applied'
      preLoaderRoute: typeof AdvisorAppliedRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/customers': {
      id: '/advisor/customers'
      path: '/customers'
      fullPath: '/advisor/customers'
      preLoaderRoute: typeof AdvisorCustomersRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/earnings': {
      id: '/advisor/earnings'
      path: '/earnings'
      fullPath: '/advisor/earnings'
      preLoaderRoute: typeof AdvisorEarningsRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/inbox': {
      id: '/advisor/inbox'
      path: '/inbox'
      fullPath: '/advisor/inbox'
      preLoaderRoute: typeof AdvisorInboxRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/login': {
      id: '/advisor/login'
      path: '/login'
      fullPath: '/advisor/login'
      preLoaderRoute: typeof AdvisorLoginRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/notes': {
      id: '/advisor/notes'
      path: '/notes'
      fullPath: '/advisor/notes'
      preLoaderRoute: typeof AdvisorNotesRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/profile': {
      id: '/advisor/profile'
      path: '/profile'
      fullPath: '/advisor/profile'
      preLoaderRoute: typeof AdvisorProfileRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/readings': {
      id: '/advisor/readings'
      path: '/readings'
      fullPath: '/advisor/readings'
      preLoaderRoute: typeof AdvisorReadingsRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/settings': {
      id: '/advisor/settings'
      path: '/settings'
      fullPath: '/advisor/settings'
      preLoaderRoute: typeof AdvisorSettingsRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/signup': {
      id: '/advisor/signup'
      path: '/signup'
      fullPath: '/advisor/signup'
      preLoaderRoute: typeof AdvisorSignupRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/todo': {
      id: '/advisor/todo'
      path: '/todo'
      fullPath: '/advisor/todo'
      preLoaderRoute: typeof AdvisorTodoRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisors/': {
      id: '/advisors/'
      path: '/advisors'
      fullPath: '/advisors/'
      preLoaderRoute: typeof AdvisorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors/$id': {
      id: '/advisors/$id'
      path: '/advisors/$id'
      fullPath: '/advisors/$id'
      preLoaderRoute: typeof AdvisorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pay': {
      id: '/api/pay'
      path: '/api/pay'
      fullPath: '/api/pay'
      preLoaderRoute: typeof ApiPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qa-state': {
      id: '/api/qa-state'
      path: '/api/qa-state'
      fullPath: '/api/qa-state'
      preLoaderRoute: typeof ApiQaStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/$id': {
      id: '/reading/$id'
      path: '/reading/$id'
      fullPath: '/reading/$id'
      preLoaderRoute: typeof ReadingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$id': {
      id: '/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wait/$id': {
      id: '/wait/$id'
      path: '/wait/$id'
      fullPath: '/wait/$id'
      preLoaderRoute: typeof WaitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support/': {
      id: '/admin/support/'
      path: '/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AdminSupportIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/support/$id': {
      id: '/admin/support/$id'
      path: '/support/$id'
      fullPath: '/admin/support/$id'
      preLoaderRoute: typeof AdminSupportIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/advisor/customers/$id': {
      id: '/advisor/customers/$id'
      path: '/$id'
      fullPath: '/advisor/customers/$id'
      preLoaderRoute: typeof AdvisorCustomersIdRouteImport
      parentRoute: typeof AdvisorCustomersRoute
    }
    '/advisor/profile/edit': {
      id: '/advisor/profile/edit'
      path: '/edit'
      fullPath: '/advisor/profile/edit'
      preLoaderRoute: typeof AdvisorProfileEditRouteImport
      parentRoute: typeof AdvisorProfileRoute
    }
    '/advisor/session/$id': {
      id: '/advisor/session/$id'
      path: '/session/$id'
      fullPath: '/advisor/session/$id'
      preLoaderRoute: typeof AdvisorSessionIdRouteImport
      parentRoute: typeof AdvisorRouteRoute
    }
    '/advisor/settings/blocked': {
      id: '/advisor/settings/blocked'
      path: '/blocked'
      fullPath: '/advisor/settings/blocked'
      preLoaderRoute: typeof AdvisorSettingsBlockedRouteImport
      parentRoute: typeof AdvisorSettingsRoute
    }
    '/advisor/settings/faq': {
      id: '/advisor/settings/faq'
      path: '/faq'
      fullPath: '/advisor/settings/faq'
      preLoaderRoute: typeof AdvisorSettingsFaqRouteImport
      parentRoute: typeof AdvisorSettingsRoute
    }
    '/advisor/settings/replies': {
      id: '/advisor/settings/replies'
      path: '/replies'
      fullPath: '/advisor/settings/replies'
      preLoaderRoute: typeof AdvisorSettingsRepliesRouteImport
      parentRoute: typeof AdvisorSettingsRoute
    }
    '/advisor/settings/reviews': {
      id: '/advisor/settings/reviews'
      path: '/reviews'
      fullPath: '/advisor/settings/reviews'
      preLoaderRoute: typeof AdvisorSettingsReviewsRouteImport
      parentRoute: typeof AdvisorSettingsRoute
    }
    '/advisor/settings/security': {
      id: '/advisor/settings/security'
      path: '/security'
      fullPath: '/advisor/settings/security'
      preLoaderRoute: typeof AdvisorSettingsSecurityRouteImport
      parentRoute: typeof AdvisorSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdvisorsRoute: typeof AdminAdvisorsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrustedRoute: typeof AdminTrustedRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSupportIdRoute: typeof AdminSupportIdRoute
  AdminSupportIndexRoute: typeof AdminSupportIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdvisorsRoute: AdminAdvisorsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrustedRoute: AdminTrustedRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSupportIdRoute: AdminSupportIdRoute,
  AdminSupportIndexRoute: AdminSupportIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AdvisorCustomersRouteChildren {
  AdvisorCustomersIdRoute: typeof AdvisorCustomersIdRoute
}

const AdvisorCustomersRouteChildren: AdvisorCustomersRouteChildren = {
  AdvisorCustomersIdRoute: AdvisorCustomersIdRoute,
}

const AdvisorCustomersRouteWithChildren =
  AdvisorCustomersRoute._addFileChildren(AdvisorCustomersRouteChildren)

interface AdvisorProfileRouteChildren {
  AdvisorProfileEditRoute: typeof AdvisorProfileEditRoute
}

const AdvisorProfileRouteChildren: AdvisorProfileRouteChildren = {
  AdvisorProfileEditRoute: AdvisorProfileEditRoute,
}

const AdvisorProfileRouteWithChildren = AdvisorProfileRoute._addFileChildren(
  AdvisorProfileRouteChildren,
)

interface AdvisorSettingsRouteChildren {
  AdvisorSettingsBlockedRoute: typeof AdvisorSettingsBlockedRoute
  AdvisorSettingsFaqRoute: typeof AdvisorSettingsFaqRoute
  AdvisorSettingsRepliesRoute: typeof AdvisorSettingsRepliesRoute
  AdvisorSettingsReviewsRoute: typeof AdvisorSettingsReviewsRoute
  AdvisorSettingsSecurityRoute: typeof AdvisorSettingsSecurityRoute
}

const AdvisorSettingsRouteChildren: AdvisorSettingsRouteChildren = {
  AdvisorSettingsBlockedRoute: AdvisorSettingsBlockedRoute,
  AdvisorSettingsFaqRoute: AdvisorSettingsFaqRoute,
  AdvisorSettingsRepliesRoute: AdvisorSettingsRepliesRoute,
  AdvisorSettingsReviewsRoute: AdvisorSettingsReviewsRoute,
  AdvisorSettingsSecurityRoute: AdvisorSettingsSecurityRoute,
}

const AdvisorSettingsRouteWithChildren = AdvisorSettingsRoute._addFileChildren(
  AdvisorSettingsRouteChildren,
)

interface AdvisorRouteRouteChildren {
  AdvisorActivityRoute: typeof AdvisorActivityRoute
  AdvisorAppliedRoute: typeof AdvisorAppliedRoute
  AdvisorCustomersRoute: typeof AdvisorCustomersRouteWithChildren
  AdvisorEarningsRoute: typeof AdvisorEarningsRoute
  AdvisorInboxRoute: typeof AdvisorInboxRoute
  AdvisorLoginRoute: typeof AdvisorLoginRoute
  AdvisorNotesRoute: typeof AdvisorNotesRoute
  AdvisorProfileRoute: typeof AdvisorProfileRouteWithChildren
  AdvisorReadingsRoute: typeof AdvisorReadingsRoute
  AdvisorSettingsRoute: typeof AdvisorSettingsRouteWithChildren
  AdvisorSignupRoute: typeof AdvisorSignupRoute
  AdvisorTodoRoute: typeof AdvisorTodoRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
  AdvisorSessionIdRoute: typeof AdvisorSessionIdRoute
}

const AdvisorRouteRouteChildren: AdvisorRouteRouteChildren = {
  AdvisorActivityRoute: AdvisorActivityRoute,
  AdvisorAppliedRoute: AdvisorAppliedRoute,
  AdvisorCustomersRoute: AdvisorCustomersRouteWithChildren,
  AdvisorEarningsRoute: AdvisorEarningsRoute,
  AdvisorInboxRoute: AdvisorInboxRoute,
  AdvisorLoginRoute: AdvisorLoginRoute,
  AdvisorNotesRoute: AdvisorNotesRoute,
  AdvisorProfileRoute: AdvisorProfileRouteWithChildren,
  AdvisorReadingsRoute: AdvisorReadingsRoute,
  AdvisorSettingsRoute: AdvisorSettingsRouteWithChildren,
  AdvisorSignupRoute: AdvisorSignupRoute,
  AdvisorTodoRoute: AdvisorTodoRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
  AdvisorSessionIdRoute: AdvisorSessionIdRoute,
}

const AdvisorRouteRouteWithChildren = AdvisorRouteRoute._addFileChildren(
  AdvisorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AdvisorRouteRoute: AdvisorRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  ApplyRoute: ApplyRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  MembershipRoute: MembershipRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  WorkRoute: WorkRoute,
  AdvisorsIdRoute: AdvisorsIdRoute,
  ApiPayRoute: ApiPayRoute,
  ApiQaStateRoute: ApiQaStateRoute,
  ReadingIdRoute: ReadingIdRoute,
  SupportIdRoute: SupportIdRoute,
  WaitIdRoute: WaitIdRoute,
  AdvisorsIndexRoute: AdvisorsIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
